name: echojar
description: "EchoJar gives you a chance to store your memories and voices that can be opened after certain time"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  go_router: 15.1.2
  provider: ^6.1.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_sound: ^9.28.0
  just_audio: ^0.10.4
  fluttertoast: ^8.2.12
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.2
  showcaseview: ^4.0.1
  flutter_local_notifications: ^19.2.1
  flutter_timezone: ^4.1.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  objectbox_generator: ^4.1.0
  go_router_builder: 2.7.5
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400 # Regular
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700 # Bold
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
